In [1]:
from PIL import Image
import numpy as np
import math
from tqdm import tqdm
from sklearn import metrics

/Users/yehiaabdelmohsen/opt/anaconda3/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.1)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


In [2]:
TRAIN_PATH = 'Train/'
TEST_PATH = 'Test/'

In [3]:
# Train images
images = []
labels = []
for i in tqdm(range(0,2401)):
  if i!=2400:
    im = Image.open(f'{TRAIN_PATH}{i+1}.jpg')
    im = np.asarray(im)
    im = im.reshape(784)
    im = np.append(im,[1])
    labels.append(math.trunc(i/240))
    images.append(im)

100%|██████████| 2401/2401 [00:01<00:00, 2281.74it/s]


In [4]:
# Test images
images_test = []
labels_test = []
for i in tqdm(range(0,201)):
    if i!=200:
        im = Image.open(f'{TEST_PATH}{i+1}.jpg')
        im = np.asarray(im)
        im = im.reshape(784)
        im = np.append(im,[1])
        labels_test.append(math.trunc(i/20))
        images_test.append(im)

100%|██████████| 201/201 [00:00<00:00, 2164.20it/s]


In [5]:
def perceptron(data, rate, labels,epochs):
  w = np.tile(np.append(1,np.zeros(784)),(10,1)) # weights for the 10 digits 10*785 matrix
  im = data.copy()
  lab = labels.copy()
  for j in tqdm(range(10)):
    l =[]
    for k in range(len(im)):
      if lab[k]!=j:
        l.append(-1)
      else:
        l.append(1)
    for i in range(epochs):
      for z in range(len(im)): # going through all the points for each epoch and breaking when we find a misclassified point
        y = np.matmul(w[j],im[z])
        if y*l[z]<0:
          w[j] = w[j] + np.multiply(im[z],rate*l[z])
          break

  return w

In [6]:
def predict(weights,label,data):
  d = data.copy()
  labels = label.copy()
  w = weights.copy()
  pred = []
  for i in range(len(data)):
    t = np.argmax(np.dot(w,d[i]))
    pred.append(t)
  print("Accuracy:",metrics.accuracy_score(labels, pred))
  print(metrics.confusion_matrix(labels, pred))


### η=1


In [7]:
w1 = perceptron(data = images, rate =1, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:30<00:00,  3.08s/it]


In [8]:
predict(w1,labels_test,images_test)

Accuracy: 0.72
[[18  0  0  0  0  0  1  1  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  1 17  1  0  0  0  0  1  0]
 [ 0  0  1 19  0  0  0  0  0  0]
 [ 0  0  1  3 16  0  0  0  0  0]
 [ 0  0  2 10  0  7  0  0  1  0]
 [ 0  0  5  0  0  0 15  0  0  0]
 [ 0  0  0  4  0  0  0 16  0  0]
 [ 0  0  0  5  0  1  0  0 14  0]
 [ 0  0  4  3  7  0  0  4  0  2]]



### η=0.1

In [9]:
w2 = perceptron(data = images, rate =0.1, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:32<00:00,  3.23s/it]


In [10]:
predict(w2,labels_test,images_test)

Accuracy: 0.72
[[18  0  0  0  0  0  1  1  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  1 17  1  0  0  0  0  1  0]
 [ 0  0  1 19  0  0  0  0  0  0]
 [ 0  0  1  3 16  0  0  0  0  0]
 [ 0  0  2 10  0  7  0  0  1  0]
 [ 0  0  5  0  0  0 15  0  0  0]
 [ 0  0  0  4  0  0  0 16  0  0]
 [ 0  0  0  5  0  1  0  0 14  0]
 [ 0  0  4  3  7  0  0  4  0  2]]


### η=0.01

In [11]:
w3 = perceptron(data = images, rate =0.01, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:31<00:00,  3.15s/it]


In [12]:
predict(w3,labels_test,images_test)

Accuracy: 0.72
[[18  0  0  0  0  0  1  1  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  1 17  1  0  0  0  0  1  0]
 [ 0  0  1 19  0  0  0  0  0  0]
 [ 0  0  1  3 16  0  0  0  0  0]
 [ 0  0  2 10  0  7  0  0  1  0]
 [ 0  0  5  0  0  0 15  0  0  0]
 [ 0  0  0  4  0  0  0 16  0  0]
 [ 0  0  0  5  0  1  0  0 14  0]
 [ 0  0  4  3  7  0  0  4  0  2]]


### η=0.001

In [13]:
w4 = perceptron(data = images, rate =0.001, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:30<00:00,  3.08s/it]


In [14]:
predict(w4,labels_test,images_test)

Accuracy: 0.735
[[18  0  0  0  0  0  1  1  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  1 16  1  1  0  0  0  1  0]
 [ 0  0  0 19  1  0  0  0  0  0]
 [ 0  0  1  1 18  0  0  0  0  0]
 [ 0  0  1 12  1  5  0  0  1  0]
 [ 0  0  4  0  0  0 16  0  0  0]
 [ 0  0  0  2  0  0  0 18  0  0]
 [ 0  0  0  4  0  1  0  0 15  0]
 [ 0  0  3  2  8  0  0  5  0  2]]


### η=0.0001

In [15]:
w5 = perceptron(data = images, rate =0.0001, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:32<00:00,  3.23s/it]


In [16]:
predict(w5,labels_test,images_test)

Accuracy: 0.73
[[18  0  0  0  0  0  1  1  0  0]
 [ 0 19  1  0  0  0  0  0  0  0]
 [ 0  1 16  1  0  0  0  1  1  0]
 [ 0  0  2 18  0  0  0  0  0  0]
 [ 0  0  1  3 16  0  0  0  0  0]
 [ 0  0  3  8  0  9  0  0  0  0]
 [ 0  0  4  0  0  0 16  0  0  0]
 [ 0  0  0  2  0  0  0 18  0  0]
 [ 0  0  2  4  0  1  0  0 12  1]
 [ 0  0  5  1  6  0  0  4  0  4]]


### η=0.00001

In [17]:
w6 = perceptron(data = images, rate =0.00001, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:31<00:00,  3.15s/it]


In [18]:
predict(w6,labels_test,images_test)

Accuracy: 0.79
[[18  0  0  0  1  0  1  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  1 16  1  1  0  0  0  1  0]
 [ 0  0  0 18  2  0  0  0  0  0]
 [ 0  0  1  0 17  0  0  0  2  0]
 [ 0  0  2  6  0 11  0  0  1  0]
 [ 0  0  3  0  0  0 17  0  0  0]
 [ 0  0  0  2  0  0  0 18  0  0]
 [ 0  0  0  1  0  0  0  0 19  0]
 [ 1  0  3  1  5  0  0  4  2  4]]


### η=0.000001

In [19]:
w7 = perceptron(data = images, rate =0.000001, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:31<00:00,  3.12s/it]


In [20]:
predict(w7,labels_test,images_test)

Accuracy: 0.67
[[18  0  0  0  1  0  1  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  1 16  1  1  0  0  0  1  0]
 [ 0  0  1 19  0  0  0  0  0  0]
 [ 0  0  1  4 15  0  0  0  0  0]
 [ 0  0  2  9  1  8  0  0  0  0]
 [ 0  0  5  0  0  0 15  0  0  0]
 [ 0  0  1  2  7  0  0 10  0  0]
 [ 0  0  0 10  0  0  0  0  8  2]
 [ 0  0  3  2  7  0  0  3  0  5]]


### η=0.0000001

In [21]:
w8 = perceptron(data = images, rate =0.0000001, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:27<00:00,  2.76s/it]


In [22]:
predict(w8,labels_test,images_test)

Accuracy: 0.68
[[19  0  0  0  1  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 19  0  0  0  1  0  0  0]
 [ 0  0  2 18  0  0  0  0  0  0]
 [ 0  1  1  1 16  0  0  0  1  0]
 [ 2  0  1 11  0  6  0  0  0  0]
 [ 0  0  3  0  2  1 14  0  0  0]
 [ 1  0  1  1  4  0  0 13  0  0]
 [ 1  0  3  4  0  2  0  0 10  0]
 [ 1  0  4  3  9  0  0  2  0  1]]


### η=0.00000001

In [23]:
w9 = perceptron(data = images, rate =0.00000001, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:18<00:00,  1.83s/it]


In [24]:
predict(w9,labels_test,images_test)

Accuracy: 0.27
[[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 4  2 14  0  0  0  0  0  0  0]
 [ 3  3 14  0  0  0  0  0  0  0]
 [ 5  6  9  0  0  0  0  0  0  0]
 [14  1  3  2  0  0  0  0  0  0]
 [11  0  9  0  0  0  0  0  0  0]
 [15  2  3  0  0  0  0  0  0  0]
 [11  4  5  0  0  0  0  0  0  0]
 [ 9  1 10  0  0  0  0  0  0  0]]


### η=0.000000001

In [25]:
w10 = perceptron(data = images, rate =0.000000001, labels=labels, epochs=1000)

100%|██████████| 10/10 [00:06<00:00,  1.47it/s]


In [26]:
predict(w10,labels_test,images_test)

Accuracy: 0.2
[[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [18  2  0  0  0  0  0  0  0  0]
 [17  3  0  0  0  0  0  0  0  0]
 [13  7  0  0  0  0  0  0  0  0]
 [19  1  0  0  0  0  0  0  0  0]
 [17  3  0  0  0  0  0  0  0  0]
 [13  7  0  0  0  0  0  0  0  0]
 [18  2  0  0  0  0  0  0  0  0]
 [16  4  0  0  0  0  0  0  0  0]]
